# Licensed under the MIT License.
# For details on the licensing terms, see the LICENSE file.
# SPDX-License-Identifier: MIT

# Copyright 2024-2025 (c) Fraunhofer IOSB (Author: Johannes Engel)
# Copyright 2024-2025 (c) Fraunhofer IOSB (Author: Florian Düwel)


services:

  visualisation_tool:
    hostname: visualisation_tool
    build: .
    expose:
      - 8083
      - 1883
      - 1884
      - 3000
      - 4000
      - 4001
      - 4002
      - 4003
    ports:
      - "8083:8083"
      - "1883:1883"
      - "1884:1884"
      - "3000:3000"
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - demonstration_scenario_network

  device_registry:
    image: ghcr.io/swap-it/demo-scenario/device_registry:execution_engine_tests
    hostname: device_registry
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - demonstration_scenario_network

  service_server:
    image: ghcr.io/swap-it/demo-scenario/demo-scenario:execution_engine_tests
    hostname: service_server
    expose:
      - 4051
      - 4061
      - 4071
      - 4081
      - 4082
      - 4083
      - 4091
      - 4092
      - 4093
    ports:
      - "4051:4051"
      - "4061:4061"
      - "4071:4071"
      - "4081:4081"
      - "4082:4082"
      - "4083:4083"
      - "4091:4091"
      - "4092:4092"
      - "4093:4093"
    networks:
      - demonstration_scenario_network

  dashboard:
    image: ghcr.io/swap-it/demo-scenario/dashboard:latest
    hostname: dashboard
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - demonstration_scenario_network

  ClientInterface:
    image: ghcr.io/swap-it/demo-scenario/client_interface:latest
    hostname: clientinterface
    expose:
      - 8181
    ports:
      - "8181:8181"
    networks:
      - demonstration_scenario_network

networks:
  demonstration_scenario_network:
    driver: "bridge"
