# Licensed under the MIT License.
# For details on the licensing terms, see the LICENSE file.
# SPDX-License-Identifier: MIT

# Copyright 2024-2025 (c) Fraunhofer IOSB (Author: Johannes Engel)


## WebSocket Listener
listener 8083
protocol websockets

# MQTT Listener v5
# Erlaubt Verbindungen auf allen IP-Adressen
listener 1884
bind_address 0.0.0.0
protocol mqtt

# Log-Einstellungen
log_dest file /var/log/mosquitto/mosquitto.log

# Persistenz
persistence true
persistence_location /var/lib/mosquitto/

# Zusätzliche Konfigurationen einbeziehen
include_dir /etc/mosquitto/conf.d

allow_anonymous true